# Google services
google_analytics: UA-79528055-1

# Content
core_pages_list:
  "Home": '/'
  "Semantic Specification": '/spec'
  "Data Conventions": '/data'
  "Contributors": '/contributors'
  "News and Notes": '/updates'

user_pages_list:
  "APIs and Supported Tracers": '/integration'
  "Instrumentation Use Cases": '/use-cases'
  "Cross-Process Propagation": '/propagation'
  "Instrument Systems at Scale": '/instrumenting-large-systems'

implementor_pages_list:
  "Implementing OpenTracing": '/implementors'
  "RPC/IPC Frameworks": '/instrumenting-ipc-frameworks'

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  hard_wrap: false

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions
  - jekyll-coffeescript

# Permalinks
permalink:        pretty

# Setup
title:            The OpenTracing Project
tagline:          'Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation'
description:      'Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation'
url:              http://opentracing.io
baseurl:          /

author:
  name:           'The OpenTracing Authors'
  url:            http://opentracing.io

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/opentracing
